language: rust

os:
  - linux

addons:
  apt:
    packages:
      - gfortran
      - libopenblas-base
      - libopenblas-dev

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test -vv --features openblas-src/system
