[package]
name = "arima"
description = "ARIMA time series modeling for Rust."
version = "0.1.3"
authors = ["Kai Fricke <coding@kaifricke.com>"]
edition = "2018"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/krfricke/arima"
repository = "https://github.com/krfricke/arima"

exclude = [
    ".idea/",
]

[badges]
travis-ci = { repository = "krfricke/arima", branch = "master" }

[features]
default = []
openblas = ["lapack", "openblas-src"]
accelerate = ["lapack", "accelerate-src"]
intel-mkl = ["lapack", "intel-mkl-src"]
netlib = ["lapack", "netlib-src"]

[dependencies]
lbfgs = "0.2.1"
more-asserts = "0.2.1"
num = "0.2.0"
optimization = "0.1.0"
rand = "0.6.5"

[dependencies.lapack]
lapack = "0.16.0"
lapack-sys = "0.12.0"
optional = true

[dependencies.accelerate-src]
version = "0.3"
optional = true

[dependencies.intel-mkl-src]
version = "0.4"
optional = true

[dependencies.netlib-src]
version = "0.7"
optional = true

[dependencies.openblas-src]
version = "0.7"
optional = true