[package]
name = "arima"
description = "ARIMA time series modeling for Rust."
version = "0.1.0"
authors = ["Kai Fricke <coding@kaifricke.com>"]
edition = "2018"
license = "Apache-2.0"
license-file = "LICENSE"
homepage = "https://github.com/krfricke/arima"
repository = "https://github.com/krfricke/arima"

exclude = [
    ".idea/",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
travis-ci = { repository = "krfricke/arima", branch = "master" }

[dependencies]
lapack = "0.16.0"
lapack-sys = "0.12.0"
openblas-src = { version = "0.7.0", features = ["system"]}
more-asserts = "0.2.1"
num = "0.2.0"
rand = "0.6.5"